spring:
  application:
    name: parking-enforcement

  rabbitmq:
    username: admin
    password: cas735

logging.level:
  ca.mcmaster.cas735.tmt.parking_enforcement:
    adapter:  INFO # DEBUG for fine-grained trace
    business: INFO

server:
  port: 9082

app:
  custom:
    mqtt:
      port: 1884
      topic: acme_parking_enforcement
    messaging:
      inbound-exchange-client: client_license
      inbound-exchange-management: manager2enforcement_msg
      outbound-exchange-management: enforcement2manager_msg
      outbound-exchange-payment: enforcement2payment_msg
      outbound-exchange-gate: enforcement2gate_msg


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'

eureka:
  client:
    healthcheck:
      enabled: true

search:
  url: http://localhost:9080