spring:
  rabbitmq:
    username: admin
    password: cas735
    host: localhost
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking-payment
    username: root
    password: mzh1501130304
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: parking-payment

logging.level:
  ca.mcmaster.cas735.lucky7.parking.payment:
    adapter:  INFO # DEBUG for fine-grained trace
    business: INFO
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # 绑定参数详情
    com.mysql.cj: DEBUG

server:
  port: 8081

app:
    messaging:
      inbound-exchange-enforcement: enforcement2payment_msg
      inbound-exchange-gate: gate2payment_msg
      inbound-exchange-manager: manager2payment_msg
      inbound-exchange-bank: in_bank_msg
      inbound-exchange-avl: availability2payment_msg
      outbound-exchange-bank: out_payment_msg
      outbound-exchange-pos: payment2pos_msg
      outbound-exchange-gate: payment2gate_msg
      outbound-exchange-manager: payment2manager_msg
      outbound-exchange-Mac: out_mac_msg
      outbound-exchange-avl: payment2availability_msg

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'

eureka:
  client:
    healthcheck:
      enabled: true

