spring:
    application:
        name: gate_system

    rabbitmq:
        username: admin
        password: cas735
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/parking-transponder
        username: root
        password: mzh1501130304
    jpa:
        hibernate:
            ddl-auto: update


logging.level:
    ca.mcmaster.cas735.acme.parking.gate_system:
        adapter:  INFO # DEBUG for fine-grained trace
        business: INFO

server:
    port: 9080

app:
    custom:
        mqtt:
            host: localhost
            port: 1883
            transponderTopic: transponder
            qrTopic: qrcode
            buttonClickTopic: buttonClick
        messaging:
            inbound-exchange-payment_ID: payment2gateConfirmation_msg
            inbound-exchange-payment_confirmation: payment2gateID_msg
            outbound-exchange-payment: gate2payment_msg

management:
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: info,health
            base-path: /actuator

info:
    application:
        description: '@project.description@'
        version:     '@project.version@'

eureka:
    client:
        healthcheck:
            enabled: true

