spring:
    application:
        name: gate_system

    rabbitmq:
        username: admin
        password: cas735
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://parking-gate-db:3306/parking-gate
        username: root
        password: mzh1501130304
    jpa:
        hibernate:
            ddl-auto: update


logging.level:
    ca.mcmaster.cas735.acme.parking.gate_system:
        adapter:  INFO # DEBUG for fine-grained trace
        business: INFO

server:
    port: 9081

app:
    custom:
        mqtt:
            host: localhost
            port: 1883
            transponderTopic: transponder
            qrTopic: qrcode
            buttonClickTopic: buttonClick

        messaging:
            inbound-exchange-payment: payment2gate_msg
            inbound-exchange-management: manager2gate_msg
            inbound-exchange-enforcement: enforcement2gate_msg
            inbound-exchange-availability: availability2gate_msg
            outbound-exchange-payment: gate2payment_msg
            outbound-exchange-management: gate2manager_msg
            outbound-exchange-availability: gate2availability_msg

management:
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: info,health
            base-path: /actuator

info:
    application:
        description: '@project.description@'
        version:     '@project.version@'

eureka:
    client:
        healthcheck:
            enabled: true

