spring:
  application:
    name: parking-availability

  rabbitmq:
    username: admin
    password: cas735

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://parking-availability-db:3306/parking-availability
    username: root
    password: mzh1501130304
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  ca.mcmaster.cas735.tmt.parking_availability:
    adapter:  INFO # DEBUG for fine-grained trace
    business: INFO

server:
  port: 9083

app:
  custom:
    mqtt:
      host: localhost
      port: 1883
      monitorTopic: monitortopic
      clientId: availabilityId

    messaging:
      inbound-exchange-topic: monitor-req
      inbound-exchange-gate: gate2availability_msg
      inbound-exchange-manager: manager2availability_msg
      inbound-exchange-payment: payment2availability_msg
      outbound-exchange-topic: monitor
      outbound-exchange-gate: availability2gate_msg
      outbound-exchange-monitor: availability2monitor_msg
      outbound-exchange-payment: availability2payment_msg
      outbound-exchange-management: availability2manager_msg

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator

info:
  application:
    description: '@project.description@'
    version:     '@project.version@'

eureka:
  client:
    healthcheck:
        enabled: true

