# Overriding configuration when started in docker mode
# to start in local mode with maven: -Dspring-boot.run.profiles=docker

spring:
  rabbitmq:
    host: rabbitmq
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/parking-transponder/?useSSL=false&serverTimezone=UTC
    username: root
    password: mzh1501130304
  jpa:
    hibernate:
      ddl-auto: update

app:
  custom:
    mqtt:
      host: rabbitmq


info:
  application:
    name: '@project.name@ (docker deployment)'

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/